### PR TITLE
Add EPICS motor record support

### PR DESCRIPTION
**Pull request by MarkRivers**
This PR adds motor record support.

### CODE REVIEW

**Comment by MarkRivers** [comment]
This includes the following changes:

- Changes to the SymetrieHexapod driver:
  - Changed the iocsh command and constructor to add movingPollPeriod and idlePollPeriod arguments
  - Added new methods to the SymetrieHexapod class (report(), poll(), getAxis())
  - Adds methods for the SymetrieAxis class (move(), stop(), poll(), etc.)
  - Initialized the position demand parameters (target positions) to the readback positions in the constructor.  This is convenient because the target positions are set to the current position of each axis when the IOC starts.
  - Removed lock() and unlock() calls in many methods.  These are not needed because this driver does not create any threads, and all of these methods are called from device support with the lock already held.
  - Made whitespace consistent in the readErrors() method.
- Added a new motor.substitutions file in the iochexapod-demo directory that loads the motor records.
- Changed st.cmd to pass movingPollPeriod and idlePollPeriod, and to load the motor.substitutions file.
- Added a related display to HexapodTop.adl for motors6x.adl to display the motor records

**Comment by MarkRivers** [comment]
@ajgdls just a reminder about this PR, thanks.

**Comment by ajgdls** [comment]
Hi @MarkRivers I had taken a look and was going to build/test against my simulator, I notice you have pushed commits for Windows today - are you finished with the commits?  Do you mind if I take a day or so to run it against a simulator I have?

**Review by ajgdls — APPROVED** [review]
Still runs up fine against my simulator.  Motor records are working and when requested to move outside the physical limitation the error message is still returned to the main application.

**Pull request merged**
